### ISSUE TITLE
webpack config question

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/worker-sites-template#2]
`mode: development` <-- any reason for this?

**Comment by Sergey-Voskresenskiy** [comment]
Of course, there is, for example, in the dev mode, you don’t need to optimize images perfectly, unlike the release mode, and there are a lot of such examples.

**Comment by xtuc** [comment]
Production is the default mode. I think it's safer to publish to worker using mode: production or omit it because webpack could rely on eval.
