### ISSUE TITLE
Autodeploy to stackbit.com

### ISSUE THREAD

**Issue by marvin-hansen** [cloudflare/worker-sites-template#37]
Alright, 

love wrangler and sites, but to get things on steroids, it would be amazing to deploy Jam sites created in Stackbit directly to CF. 

[stackbit.com](https://www.stackbit.com)

Not sure what CloudFlare needs to do for that, but please talk to the guys at stackbit b/c getting a complete JAMstack site with a headless CMS on CF in under a minute is pretty appealing not only to me.

**Comment by EverlastingBugstopper** [comment]
Hey! I'm not super familiar with stackbit buuuttt it looks like they create a static directory that links up with a github project. You could probably use Workers Sites with Stackbit with this [Github Action](https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler), although setting it up is probably a bit more manual than current existing solutions. It _should_ be a one time setup where you clone the repo created by stackbit, follow [this documentation](https://developers.cloudflare.com/workers/sites/start-from-existing/), and set up the aforementioned Github Action. Then, on future changes made in Stackbit, it should auto-deploy your Workers Site.

If you decide to try this out, please let us know how it goes!

**Comment by marvin-hansen** [comment]
Thanks for the hint,

meanwhile, I've reported a feature request to stackbit for all the reasons
you have mentioned and with a bit of luck they add a deployment option to
the orange cloud.

As for myself, I have to postpone this avenue due to a higher priority
project that came in.
