### ISSUE TITLE
Expires header

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/worker-sites-template#38]
Why don’t static assets like SVGs have an `expire` or `max-age` header?

**Comment by victoriabernard92** [comment]
Expire and max-age header will be returned on a response iff the asset is set to cache by the client (i.e. browserCache )
By default only edge caching is set and browser cache is turned off. See https://github.com/cloudflare/kv-asset-handler#browserttl

**Comment by tillkruss** [comment]
Is there a reason for this, or can I safely enable `browserTTL` for SVGs?

**Comment by victoriabernard92** [comment]
> Is there a reason for this, or can I safely enable `browserTTL` for SVGs?

Yes, you can safely apply browserTTL for images and any other resource you'd like cached on the browser
