### ISSUE TITLE
Top level sw.js is not served

### ISSUE THREAD

**Issue by jjelev** [cloudflare/worker-sites-template#41]
Consider this example:
https://some-worker.workers.dev/sw.js will return 404 instead of /sw.js

**Comment by ashleymichal** [comment]
hey @jjelev !
what does the `site` section of your wrangler.toml look like? just want to confirm you're all set up.

**Comment by jjelev** [comment]
I am changing the name because it is working for other assets.

**Comment by jjelev** [comment]
@ashleymichal This is the only rule I gave in order to serve nuxt.js project
```toml
[site]
bucket = "./dist"
```

**Comment by ashleymichal** [comment]
hrm. so wrangler uses webpack, and webpack writes to the `./dist` directory with the final webpacked worker script. just to test, try renaming your bucket directory to something like `./public` and see if the problem persists.

**Comment by jjelev** [comment]
Yes, I noticed that. The final worker script is  `dist/main.js` which I don't have in normal build.
I other test I did is to rename sw.js to new-sw.js and it my app loads the service worker fine.
So there is something special with `sw.js`.

**Comment by jjelev** [comment]
I created a discussion on [Cloudflare fourum](https://community.cloudflare.com/t/worker-sites-dont-serve-sw-js/144587).

**Comment by johntunnel** [comment]
I have similar problem with following file:
wp-includes/css/dist/block-library/style.min.css
I am not sure if wrangler does not upload this file or Cloudflare does not serve it. Do not know how to check this.
Reply from cloudflare is "could not find... in your namespace"
Own domain or workers.dev is the same. 
Only this file out of 1300 files has problem to show up.

**Comment by EverlastingBugstopper** [comment]
This may be related to #40 - wrangler will not upload any files that are listed in your `.gitignore`

**Comment by jjelev** [comment]
Checked again and **sw.js** works on my worker sites.
No longer reproducible. Probably fixed by Cloudflare.
